### PR TITLE
Add diffing of before/after examples

### PR DESCRIPTION
**Pull request by isomorpheme**

### CODE REVIEW

**Comment by elland** [comment]
@isomorpheme once this is ready, would be nice to have screenshots showing the diffing. :D I also hope it's easy enough to style them after?

**Comment by isomorpheme** [comment]
Shouldn't be too hard yeah, I think the easiest would be to add a `<span>` around the changed lines with either `class="removed"` or `class="added"`.

**Comment by isomorpheme** [comment]
By the way, I'm trying to make a 2-column diff because it differs the least from the existing layout, but I'm curious if people have ideas for other setups. E.g. maybe it'd be nice if examples had a structure where first it shows the before files as-is, then the error, and then a diff for the after files. (Not sure where the explanation section would fit in best, though.)

**Comment by PPKFS** [comment]
Should we close in favour of #180 ?

**Comment by isomorpheme** [comment]
Yes, #180 replaces this one, forgot to mention sooner. :)

**Pull request closed without merging**
