### PR TITLE
Generate CSS and use B612 for numbering.

### PR DESCRIPTION
**Pull request by philderbeast**
Use B612 font for number codes and for the message and use sass to generate the CSS.

https://b612-font.com/

Screen Shot 2022-06-12 at 12 21 13 PM

### CODE REVIEW

**Comment by philderbeast** [comment]
Uses ellipsis for overflow of the summary column cells that I've given a width of `30em`.

Screen Shot 2022-06-12 at 12 48 17 PM

**Comment by philderbeast** [comment]
Use the same code style in the title and breadcrumb.

Screen Shot 2022-06-12 at 1 04 26 PM

**Comment by philderbeast** [comment]
Use the same style in the examples and go with a transparent background for code snippets.

Screen Shot 2022-06-12 at 1 24 15 PM

**Comment by david-christiansen** [comment]
There are things here that I like as well as things that concern me.

First off, my biggest concern: one goal with this project is that I can maintain it with a low degree of attention and without much work over a longer period of time. I've tried to stick with technology choices that have fairly stable APIs (this is an explicit goal of Hakyll these days) as well as to keep requirements to a minimum. A whole separate package infrastructure to make the CSS file a little shorter is something that I'd like to hear a bit more of an argument for - how much is gained by using sass for this project, vs just writing the CSS? I think I have a good idea of the costs, but not really of the benefits.

Secondly, I'm a bit confused about the typography. Why are message page titles written in monospace? They're not direct quotes that should be entered into a computer, nor are they code where layout should be preserved. From my perspective, they're like all other page titles, but here the typography is indicating otherwise. What's the thought process there?

What are your thoughts on the ellipsis, vs having the summary on the line below the code and the title? E.g.
```
| GHC-12345 | Couldn't unify kinds | 9.6    |
| The kinds are unavailable for unification | 
````
Then a bit of vertical space could separate things. I think this might be more scannable than the little table here. Thoughts? The ellipses are nicer than our current setup for sure.

**Comment by david-christiansen** [comment]
Oh, and thank you!

**Comment by serras** [comment]
@philderbeast maybe using the [`hakyll-sass`](https://hackage.haskell.org/package/hakyll-sass-0.2.3/docs/Hakyll-Web-Sass.html) would get us the benefits of using SASS (maintainability, readability), but without having to involve `*npm` into this.

**Comment by david-christiansen** [comment]
That library hasn't had commits since 2018, though. That also makes me nervous!

**Comment by elland** [comment]
I'd personally prefer if we kept outside tools to a very minimum, as @david-christiansen mentioned. Having any barriers to maintain/contribute to the project is something we should avoid.

**Comment by david-christiansen** [comment]
This is why I'd like to have a better understanding of the concrete savings of sass in this particular case. If it's a somewhat small benefit for a small site like this, then I suspect that it's not worth the complexity, but if there is a big benefit that I don't yet understand, then it could very well be worth it.

But for this context, tools and dependencies are a bigger cost than for projects that are maintained on a more full-time basis, and that does change the calculus a bit.

**Comment by david-christiansen** [comment]
My concern is less that potential contributors feel strongly against sass and are thus scared off, and more that in three years when I have to come update this site, that having more dependencies that I don't understand well will get me stuck.

**Comment by gillchristian** [comment]
I don't see many benefits from introducing SASS, if the CSS stays short making it a bit shorter won't make much of a change. Also in my experience SASS nesting and all the tools for composing classes names make things even harder to understand.

:heavy_plus_sign: to keep it simple.

**Pull request closed without merging**
