### PR TITLE
Remove header links and contact

### PR DESCRIPTION
**Pull request by alt-romes**
In order to make the error index more straightforward and a bit cleaner, I've removed the contact homepage, the header linking to it, and the breadcrumbs.

I've moved the contact information to the footer and added a paragraph to the *Welcome* section with the same information

Since the information was short, it seemed that a whole page just for it was somewhat unnecessary.
By removing the Contacts page, we can also get rid of the header selection and Home title which was somewhat redundant

The breadcrumbs also seemed a bit invasive in the page, since I couldn't find a situation in which we had more than 1 level of depth. The browser "back button" navigation is already quite good, so I don't think we need to mimic it on the website

When someone visits an error code, they can use the back button which is the canonical way of going back and forth in a website

This is a bit opinionated, so let me have your comments on it

Thanks :)

### CODE REVIEW

**Comment by david-christiansen** [comment]
I want to keep the breadcrumbs. I think they're important for giving someone a sense of the page when they arrive at a link from a search engine.

The other changes sound like they might be useful simplifications though. Would you mind splitting the PR up a bit?

**Comment by alt-romes** [comment]
OK. I've redone this:

This PR removes the header links and the contact homepage altogether.
The contact information now lives in the footer and in the *Welcome* paragraph

Screenshots:
Screenshot 2022-06-15 at 17 44 08
Screenshot 2022-06-15 at 17 32 46
Screenshot 2022-06-15 at 17 44 00

**Comment by alt-romes** [comment]
Note:

This is primarily a UX related PR, having too many things that people can click on is often more confusing than not, and in this case unnecessary to have both a contact and a home, when we just trivially want to display error messages.

The design itself about where to place the titles and bars and breadcrumbs can also be reviewed, but independently of this PR

**Comment by david-christiansen** [comment]
Only one thing seems a bit off to me - why do we need the same sentence in both the footer and on the main page?

I think people can find the HF contact page if we just link to the HF. What if we get rid of the sentence in the footer? Or is there something I'm missing?

Thanks for this!

**Comment by alt-romes** [comment]
@david-christiansen When moving it out of the "Contacts" page, I wanted it to have the same visibility as if we did still have the "Contacts" page, but if you think we can get rid of it altogether then alright!

It does link to the Haskell foundation page.

I think it would be more interesting if we linked this issue tracker, what would be good wording?

Or just remove it altogether

**Comment by alt-romes** [comment]
@david-christiansen OK, I think this is ready then

I removed the header line altogether too

Current screenshots:

Screenshot 2022-06-15 at 21 59 28

Screenshot 2022-06-15 at 21 59 18

**Comment by alt-romes** [comment]
I might attempt to do something UI related, if that were to be well received.

I haven't contributed to OSS on UI related things previously, so I'm a bit unsure about how to approach things.

My fear is that in UI things are necessarily opinionated, and so don't know whether I should indeed be redesigning something that is already working and published.

However, given the "WIP" status of the error index message, perhaps trying a few designs wouldn't be bad.

Let me know,
Rodrigo

**Comment by david-christiansen** [comment]
I just tested this out, and I like the simplification. Thanks!

**Review by david-christiansen — APPROVED** [review]

**Comment by david-christiansen** [comment]
As far as redesigns go, I'm happy to take a look at them. This project is only about a 1.5 weeks old, and while it became more beautiful at ZuriHac and with your contributions, its starting point was just a tweaked default Hakyll theme.

Here's what I see as requirements for a redesign, though:
1. Minimize use of extra tools - I need to maintain this thing, so I don't want to have to learn and keep up to date with a big ecosystem of tools and pre-processors. If we can stick to CSS and JS files in a directory, that'd be a big help, even if we have to be a little repetitive in the code.
2. It should visually resemble haskell.org and haskell.foundation in the use of color and typography (that is, a green theme probably wouldn't work well)
3. It should work well for old-school Internet people who turn off their Javascript, and it should be readable on phones (the site currently fails that criterion due to my mistakes)
4. It should make clear that people should not hassle the GHC developers, but instead should contact me at the HF
5. It should prominently link to this repo and encourage community contributions. I think we could do that a lot better than we do right now.

How do you want to work together on this? Is it easiest to send mock-ups first for comment so you don't spend too much time on implementation, or are you a code-and-PR-first kind of person? Either works for me.

Thanks!

**Pull request merged**
