### PR TITLE
Document GHC-00158

### PR DESCRIPTION
**Pull request by aionescu**

### CODE REVIEW

**Comment by PPKFS** [comment]
Not a full review yet, but I think there should be at least 3 cases:

- trying to derive something that isn't stock, and needing an extension
- trying to derive a standalone new type instance 
- using detuvingstrategies and trying to explicitly stock derive a non stock class

**Comment by PPKFS** [comment]
Okay my second point is not needed -- there's some weirdness that goes on with newtype deriving. But having an example of where the requirement is that you've explicitly stated a deriving strategy and chosen a wrong one would be good

**Comment by david-christiansen** [comment]
I think it's OK to merge something where we would like more examples. The site is a living document, and we expect it to persist over time and accrete more and more useful things.

**Review by PPKFS — APPROVED** [review]

**Comment by PPKFS** [comment]
Definitely agree. Approved and I'll flag up an issue so it's not lost :)

**Pull request merged**
