### PR TITLE
Highlighting and improvements to examples

### PR DESCRIPTION
**Pull request by serras**
This adds highlighting via [highlight.js](https://highlightjs.org/). The JS and CSS files are copied, so we don't need to go to a CDN.

This also gives a bit of love to the examples. The list-based template is changed to a table, and some CSS attributes are defined to control how they look.

imagen

### CODE REVIEW

**Comment by elland** [comment]
@serras I was looking into doing this via pandoc directly, instead of adding a JS dependency and running that on every page load. 😅 But that's certainly better than no highlighting.

**Comment by serras** [comment]
@elland I tried to use the Pandoc highlighting mechanism too, but did not manage.

There’s one advantage to this approach, though: using Pandoc the code is transformed to an un decipherable list of tokens. With the solution in this PR search engines still see the code as written, so it can be potentially indexed.

**Comment by david-christiansen** [comment]
This is great!

**Comment by elland** [comment]
@serras I'll take a look. The way examples are loaded and rendered needs a bit of love, if we want multiple before/after examples.

**Pull request merged**
